spring:
  security:
    user:
      name: root
      password: root
  datasource:
    username: jasper
    password: Password1!
    url: jdbc:mysql://192.168.204.128:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect